import { useSession } from 'next-auth/react'
import Head from 'next/head'
import Image from 'next/image'
import Link from 'next/link'
import { useRouter } from 'next/router'
import styles from '../styles/Home.module.css'
import { LogInBtn } from '../components'

export default function Home() {
  const router = useRouter()

  const handleClick = () => {
    console.log('Placing your order')
    router.replace('/product')
  }

  const { data: session, status } = useSession()

  var signOnStatus = ''
  if ( status === 'authenticated') {
    signOnStatus = 'Welcome, '+ session.user.name
  } else {
    signOnStatus = 'You are not signed in yet.'
  }

  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Home Page
        </h1>

        <h2>{signOnStatus}</h2>
        <LogInBtn/>


        <p className={styles.description}>
          Lorem ipsum, dolor sit amet consectetur adipisicing elit. Tenetur, veritatis corrupti blanditiis nobis hic dolorem doloribus mollitia reiciendis modi reprehenderit recusandae quam quas odit amet voluptate ducimus inventore voluptatibus accusamus?
        </p>

        <div className={styles.grid}>
          <Link href="/login" className={styles.card}>
            <h2>login &rarr;</h2>
            <p>Login page</p>
          </Link>

          <Link href="/blog" className={styles.card}>
            <h2>Blog &rarr;</h2>
            <p>Some Blog page</p>
          </Link>

          <Link href="/product" className={styles.card}>
            <h2>Product &rarr;</h2>
            <p>Some product list</p>
          </Link>
          <button onClick={handleClick}>Place Order</button>

          <Link href="/users" className={styles.card}>
            <h2>Users &rarr;</h2>
            <p>User List.</p>
          </Link>

          <Link href="/posts" className={styles.card}>
            <h2>Posts &rarr;</h2>
            <p>
              Post List
            </p>
          </Link>
        </div>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span className={styles.logo}>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
